grafana:
  enabled: true
  adminUser: admin
  adminPassword: "Kingdavid69"   # change this later
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: false  # we'll create a custom ALB ingress later

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
  service:
    type: ClusterIP

alertmanager:
  enabled: true
  service:
    type: ClusterIP
