# FRONT-END
frontend:
  replicaCount: 2
  image:
    repository: weaveworksdemos/front-end
    tag: "0.3.12"
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 300m
      memory: 1000Mi
    requests:
      cpu: 100m
      memory: 300Mi
  service:
    type: NodePort  
    port: 80
    targetPort: 8079
    nodePort: 30001
