apiVersion: v1
kind: Service
metadata:
  name: catalogue
  annotations:
        prometheus.io/scrape: 'true'
  labels:
    name: catalogue
  namespace: sock-shop
spec:
  ports:
    # the port that this service should serve on
  - port: {{ .Values.catalogue.service.port }}
    targetPort: {{ .Values.catalogue.service.targetPort }}
  selector:
    name: catalogue
