apiVersion: v1
kind: Service
metadata:
  name: frontend
  annotations:
    prometheus.io/scrape: "true"
  labels:
    name: frontend
  namespace: sock-shop
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      nodePort: {{ .Values.frontend.service.nodePort }}
  selector:
    name: frontend