---
apiVersion: v1
kind: Service
metadata:
  name: session-db
  labels:
    name: session-db
  namespace: sock-shop
spec:
  ports:
    # the port that this service should serve on
  - port: {{ .Values.session.service.port }}
    targetPort: {{ .Values.session.service.targetPort }}
  selector:
    name: session-db
