apiVersion: v1
kind: Service
metadata:
  name: shipping
  annotations:
        prometheus.io/scrape: 'true'
  labels:
    name: shipping
  namespace: sock-shop
spec:
  ports:
    # the port that this service should serve on
  - port: {{ .Values.shipping.service.port }}
    targetPort: {{ .Values.shipping.service.targetPort }}
  selector:
    name: shipping

