apiVersion: v1
kind: Service
metadata:
  name: user
  annotations:
        prometheus.io/scrape: 'true'
  labels:
    name: user
  namespace: sock-shop
spec:
  ports:
    # the port that this service should serve on
  - port: {{ .Values.user.service.port }}
    targetPort: {{ .Values.user.service.targetPort }}
  selector:
    name: user

